#!/usr/bin/env python
"""
Export PySCF molecular orbitals to PyMOL-compatible formats.
Creates PDB file (structure) and cube files (orbitals).

Usage: python export_to_pymol.py <results_file.h5> --orbitals 0,1,2
"""
import sys
import numpy as np
import h5py
from pyscf import gto

def write_pdb(filename, atom_symbols, atom_coords):
    """Write molecular structure as PDB file."""
    with open(filename, 'w') as f:
        f.write("HEADER    Molecular structure from PySCF\n")
        f.write("REMARK    Generated by export_to_pymol.py\n")
        
        for i, (symbol, coord) in enumerate(zip(atom_symbols, atom_coords)):
            # PDB format: ATOM, serial, name, resName, chainID, resSeq, x, y, z, occupancy, tempFactor, element
            f.write(f"ATOM  {i+1:5d}  {symbol:<3s} MOL A   1    "
                   f"{coord[0]:8.3f}{coord[1]:8.3f}{coord[2]:8.3f}"
                   f"  1.00  0.00          {symbol:>2s}\n")
        
        f.write("END\n")

def write_cube(filename, atom_symbols, atom_coords, orbital_grid, origin, spacing):
    """
    Write orbital as Gaussian cube file.
    
    Args:
        filename: Output cube filename
        atom_symbols: List of atom symbols
        atom_coords: Atom coordinates in Bohr
        orbital_grid: 3D array of orbital values
        origin: Grid origin in Bohr
        spacing: Grid spacing in Bohr
    """
    nx, ny, nz = orbital_grid.shape
    
    with open(filename, 'w') as f:
        # Header
        f.write("Molecular orbital from PySCF\n")
        f.write("Generated by export_to_pymol.py\n")
        
        # Number of atoms and origin
        f.write(f"{len(atom_symbols):5d} {origin[0]:12.6f} {origin[1]:12.6f} {origin[2]:12.6f}\n")
        
        # Grid dimensions and spacing
        f.write(f"{nx:5d} {spacing:12.6f} {0.0:12.6f} {0.0:12.6f}\n")
        f.write(f"{ny:5d} {0.0:12.6f} {spacing:12.6f} {0.0:12.6f}\n")
        f.write(f"{nz:5d} {0.0:12.6f} {0.0:12.6f} {spacing:12.6f}\n")
        
        # Atom coordinates (atomic number, charge, x, y, z in Bohr)
        atomic_numbers = {'H': 1, 'C': 6, 'N': 7, 'O': 8, 'F': 9, 'Cl': 17, 'S': 16, 'Li': 3, 'B': 5}
        for symbol, coord in zip(atom_symbols, atom_coords):
            atomic_num = atomic_numbers.get(symbol, 0)
            f.write(f"{atomic_num:5d} {0.0:12.6f} {coord[0]:12.6f} {coord[1]:12.6f} {coord[2]:12.6f}\n")
        
        # Orbital values (6 values per line)
        values = orbital_grid.flatten()
        for i in range(0, len(values), 6):
            line_values = values[i:i+6]
            f.write(" ".join([f"{v:13.5e}" for v in line_values]) + "\n")

def export_to_pymol(h5_filename, orbital_indices, grid_points=80):
    """
    Export molecular structure and orbitals to PyMOL formats.
    
    Args:
        h5_filename: PySCF results file
        orbital_indices: List of orbital indices to export
        grid_points: Grid resolution for cube files
    """
    print(f"\nExporting to PyMOL formats...")
    print(f"Orbitals: {orbital_indices}")
    
    # Load results
    with h5py.File(h5_filename, 'r') as f:
        mo_coeff = f['mo_coeff'][:]
        mo_energy = f['mo_energy'][:]
        mo_occ = f['mo_occ'][:]
        atom_coords = f['atom_coords'][:]  # In Bohr
        atom_symbols = f.attrs['atom_symbols']
        basis = f.attrs['basis']
        molecule_name = f.attrs['molecule']
        spin = f.attrs.get('spin', 0)
    
    # Handle unrestricted (open-shell) case
    if isinstance(mo_coeff, tuple):
        mo_coeff = mo_coeff[0]
        mo_energy = mo_energy[0] if isinstance(mo_energy, tuple) else mo_energy
        mo_occ = mo_occ[0] if isinstance(mo_occ, tuple) else mo_occ
    elif mo_coeff.ndim == 3:
        mo_coeff = mo_coeff[0]
        mo_energy = mo_energy[0] if mo_energy.ndim > 1 else mo_energy
        mo_occ = mo_occ[0] if mo_occ.ndim > 1 else mo_occ
    elif mo_coeff.ndim == 1:
        # Single orbital saved - reshape to 2D
        mo_coeff = mo_coeff.reshape(-1, 1)
        mo_energy = np.array([mo_energy]) if np.isscalar(mo_energy) else mo_energy
        mo_occ = np.array([mo_occ]) if np.isscalar(mo_occ) else mo_occ
    
    # Reconstruct molecule
    atom_string = '; '.join([f"{sym} {coord[0]} {coord[1]} {coord[2]}" 
                             for sym, coord in zip(atom_symbols, atom_coords)])
    mol = gto.M(atom=atom_string, basis=basis, unit='Bohr', spin=spin)
    
    # Export structure as PDB (convert Bohr to Angstrom)
    pdb_filename = f"{molecule_name}_structure.pdb"
    atom_coords_angstrom = atom_coords * 0.529177
    write_pdb(pdb_filename, atom_symbols, atom_coords_angstrom)
    print(f"\nStructure exported: {pdb_filename}")
    
    # Create grid for orbitals
    center = np.mean(atom_coords, axis=0)
    bond_length = np.linalg.norm(atom_coords[1] - atom_coords[0]) if mol.natm > 1 else 10.0
    extent = max(bond_length * 5, 30.0)  # Bohr
    
    coords = np.linspace(-extent/2, extent/2, grid_points)
    spacing = coords[1] - coords[0]
    origin = np.array([-extent/2, -extent/2, -extent/2]) + center
    
    X, Y, Z = np.meshgrid(coords, coords, coords, indexing='ij')
    grid_coords = np.column_stack([X.ravel(), Y.ravel(), Z.ravel()]) + center
    
    # Evaluate atomic orbitals
    print("\nEvaluating orbitals on grid...")
    ao_values = mol.eval_gto('GTOval', grid_coords)
    
    # Export each orbital as cube file
    for orb_idx in orbital_indices:
        mo_values = ao_values @ mo_coeff[:, orb_idx]
        mo_grid = mo_values.reshape(grid_points, grid_points, grid_points)
        
        energy_eV = mo_energy[orb_idx] * 27.211
        occ = mo_occ[orb_idx]
        
        cube_filename = f"{molecule_name}_orbital_{orb_idx+1}_E{energy_eV:.1f}eV.cube"
        write_cube(cube_filename, atom_symbols, atom_coords, mo_grid, origin, spacing)
        
        print(f"  Orbital {orb_idx+1}: {cube_filename} (E={energy_eV:.2f} eV, occ={occ:.2f})")
    
    # Write PyMOL script
    script_filename = f"{molecule_name}_pymol.pml"
    with open(script_filename, 'w') as f:
        f.write(f"# PyMOL script for {molecule_name}\n\n")
        f.write(f"load {pdb_filename}\n")
        f.write("show spheres\n")
        f.write("set sphere_scale, 0.3\n\n")
        
        colors = ['red', 'blue', 'green', 'yellow', 'orange', 'cyan']
        for i, orb_idx in enumerate(orbital_indices):
            energy_eV = mo_energy[orb_idx] * 27.211
            cube_file = f"{molecule_name}_orbital_{orb_idx+1}_E{energy_eV:.1f}eV.cube"
            object_name = f"{molecule_name}_orbital_{orb_idx+1}_E{energy_eV:.1f}eV"  # PyMOL drops .cube
            color = colors[i % len(colors)]
            
            f.write(f"# Orbital {orb_idx+1}\n")
            f.write(f"load {cube_file}\n")
            f.write(f"isosurface orb{orb_idx+1}_pos, {object_name}, 0.02\n")
            f.write(f"isosurface orb{orb_idx+1}_neg, {object_name}, -0.02\n")
            f.write(f"color {color}, orb{orb_idx+1}_pos\n")
            f.write(f"color gray, orb{orb_idx+1}_neg\n")
            f.write(f"set transparency, 0.3, orb{orb_idx+1}_*\n\n")
        
        f.write("bg_color white\n")
        f.write("set ray_shadows, 0\n")
    
    print(f"\nPyMOL script: {script_filename}")
    print(f"\nTo visualize in PyMOL:")
    print(f"  pymol {script_filename}")
    print(f"\nOr manually:")
    print(f"  pymol {pdb_filename}")
    print(f"  Then: load orbital_*.cube files and create isosurfaces")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python export_to_pymol.py <results_file.h5> --orbitals 0,1,2")
        print("\nExamples:")
        print("  python export_to_pymol.py results_H2O_CCSD_cc-pvtz_*.h5 --orbitals 0,1,2,3,4")
        print("  python export_to_pymol.py results_HCl_CCSD_cc-pvtz_*.h5 --orbitals 4,5")
        sys.exit(1)
    
    filename = sys.argv[1]
    
    # Parse orbitals
    orbitals = None  # Default: all occupied
    for i, arg in enumerate(sys.argv):
        if arg == '--orbitals' and i + 1 < len(sys.argv):
            orbitals = [int(x) for x in sys.argv[i + 1].split(',')]
    
    # If no orbitals specified, find occupied ones
    if orbitals is None:
        import h5py
        with h5py.File(filename, 'r') as f:
            mo_occ = f['mo_occ'][:]
            if mo_occ.ndim == 0:
                mo_occ = np.array([mo_occ])
            orbitals = list(np.where(mo_occ > 0.1)[0])
        print(f"Auto-detected {len(orbitals)} occupied orbitals (occupancy > 0.1)")
    
    export_to_pymol(filename, orbitals)
